# Generated by Django 2.1.5 on 2019-05-01 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Main',
        ),
    ]
