# Generated by Django 2.1.5 on 2019-05-03 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190502_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonview',
            name='post',
        ),
        migrations.RemoveField(
            model_name='lessonview',
            name='user',
        ),
        migrations.DeleteModel(
            name='LessonView',
        ),
    ]
