# Generated by Django 2.1.5 on 2019-05-04 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190503_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='thumbnail',
        ),
    ]
