# Generated by Django 2.1.5 on 2019-05-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190504_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='categories',
            field=models.ManyToManyField(to='api.Category'),
        ),
    ]
